import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
// import "../public/font/KonexyPersonalUse.otf"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 👉 Konexy local font
const konexy = localFont({
  src: "../public/font/KonexyPersonalUse.otf",
  variable: "--font-konexy",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/lustria" rel="stylesheet"></link>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${konexy.variable}`}>
        {children}
          
      </body>
    </html>
  );
}
